on: push

name: conan

jobs:
  run-conan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        config:
          - buildtype: Release
          - buildtype: Debug

    name: ${{ matrix.config.buildtype }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install Conan
        run: pip install -U conan

      - name: Run
        shell: cmd
        env:
          CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
          CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
          BUILD_TYPE: ${{ matrix.config.buildtype }}
        run: |
          conan remote add fuel https://artifactory.anotherfoxguy.com/artifactory/api/conan/fuel-scm
          conan install . -b missing -s build_type=$BUILD_TYPE
          conan upload qt/6.2.1 -r fuel --all -f